version: "3.8"
services:
  mysql:
    image: mysql  #build the container using this image
    container_name: mysql #your container name
    environment: #Required env variables
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
    ports:
      - "3307:3306"
    volumes: #use volume's variable [-]
      - ./mysql-data:/var/lib/mysql
    networks:
      - two-tier-network
    restart: always
    healthcheck: #jab tak command ping na ho, mysql up nahi hoga
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  flask-app:
#    build:
#     context: . #dockerfile path
    image: chauhan0799/two-tier-flask-app-backend:latest #[build the container using image if available on docker hub]

    container_name: flask-app
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: devops
    networks:
      - two-tier-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on: #1st mysql service start hogi and then flask-app
      - mysql

networks: #create networks
  two-tier-network:
volumes: #create volumes
  mysql-data:
